### ISSUE TITLE
首次添加播放歌曲时报错

### ISSUE THREAD

**Issue by GOOD-AN** [luiguangguan/DGJv3#2]
报错如下
```
Id: 1904678833
网易云音乐[暂不支持登录] 本地时间：2023/12/20 21:42:41
System.NotImplementedException: The method or operation is not implemented.
   at DGJv3.InternalModule.ApiBaseModule.GetLyricById(String Id)
   at DGJv3.SearchModule.SafeGetLyricById(String Id)
```
因为会添加两首，一首正在播放，一首等待播放，所以会弹出两次相同报错。

**Comment by luiguangguan** [comment]
這種問題有可能是網易雲的接口錯誤。
你如果需要登錄網易雲音樂，需要在【網易雲喵塊】的插件中進行掃碼登錄
![image](https://github.com/user-attachments/assets/9a39c540-8cee-40aa-bc35-3c774c4c0e99)
